name: CI Pipeline (Develop)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm test

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Run Sonar Scanner
        run: |
          sonar-scanner -D"sonar.projectKey=demo-pipeline" \
                        -D"sonar.sources=." \
                        -D"sonar.host.url=http://40.82.200.144:9000" \
                        -D"sonar.login=${{ secrets.SONAR_TOKEN }}"

  dependency-track:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate SBOM
        uses: cyclonedx/cdxgen@v9
        with:
          output-format: json
          output-file: bom.json
      
      - name: Upload to Dependency-Track
        run: |
          curl -X "POST" "${{ secrets.DEPENDENCY_TRACK_URL }}/api/v1/bom" \
               -H "Content-Type: multipart/form-data" \
               -H "X-API-Key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}" \
               -F "projectName=demo-pipeline" \
               -F "projectVersion=0.0.0" \
               -F "bom=@bom.json"
